name: nlp-env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - requests
  - pandas
  - beautifulsoup4
  - openpyxl
  - jupyter
  - aiobotocore
  - aiofiles
  - aiohttp
  - aioitertools
  - aiosignal
  - aiosqlite
  - alabaster
  - altair
  - anaconda-client
  - anaconda-navigator
  - anaconda-project
  - anyio
  - appdirs
  - appnope
  - argon2-cffi
  - arrow
  - astroid
  - astropy
  - async-lru
  - attrs
  - autopep8
  - babel
  - bcrypt
  - black
  - bleach
  - bokeh
  - botocore
  - bottleneck
  - cachetools
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - click
  - cloudpickle
  - colorama
  - conda
  - conda-build
  - conda-package-handling
  - contourpy
  - cryptography
  - cycler
  - cytoolz
  - dask
  - debugpy
  - decorator
  - defusedxml
  - dill
  - distributed
  - docutils
  - entrypoints
  - executing
  - fastjsonschema
  - filelock
  - flask
  - fonttools
  - frozenlist
  - fsspec
  - future
  - gensim
  - gitdb
  - gitpython
  - h5py
  - heapdict
  - holoviews
  - httpcore
  - httpx
  - hvplot
  - idna
  - imageio
  - importlib-metadata
  - iniconfig
  - ipykernel
  - ipython
  - ipywidgets
  - isort
  - itsdangerous
  - jinja2
  - jmespath
  - joblib
  - jsonschema
  - jupyter-client
  - jupyter-console
  - jupyter-core
  - jupyterlab
  - jupyterlab-widgets
  - keyring
  - kiwisolver
  - lazy-object-proxy
  - libarchive-c
  - linkify-it-py
  - llvmlite
  - locket
  - lxml
  - lz4
  - markdown
  - matplotlib
  - matplotlib-inline
  - mistune
  - more-itertools
  - mpmath
  - msgpack
  - multipledispatch
  - mypy
  - mypy-extensions
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx
  - nltk
  - notebook
  - numba
  - numexpr
  - numpy
  - opencv-python
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - panel
  - parso
  - partd
  - pathspec
  - patsy
  - pillow
  - pip
  - pkginfo
  - plotly
  - pluggy
  - ply
  - prometheus-client
  - prompt-toolkit
  - protobuf
  - psutil
  - pure-eval
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pycodestyle
  - pycparser
  - pyjwt
  - pylint
  - pyparsing
  - pyqt5
  - pyqtwebengine
  - pysocks
  - pytest
  - python-dateutil
  - python-dotenv
  - pytz
  - pyyaml
  - pyzmq
  - regex
  - requests
  - requests-toolbelt
  - rfc3986-validator
  - rich
  - rope
  - rtree
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - six
  - smart-open
  - sniffio
  - soupsieve
  - sqlalchemy
  - stack-data
  - statsmodels
  - sympy
  - tabulate
  - terminado
  - textdistance
  - threadpoolctl
  - tifffile
  - tinycss2
  - tornado
  - tqdm
  - traitlets
  - twisted
  - typing-extensions
  - ujson
  - urllib3
  - wcwidth
  - websocket-client
  - werkzeug
  - widgetsnbextension
  - wrapt
  - xarray
  - xlwings
  - xyzservices
  - yapf
  - zict
  - zipp
  - zope.interface