name: Daily News Web-scrapping Script Run

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-nlp-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      - name: Create conda environment
        run: conda env create -f environment.yml

      - name: Run Jupyter Notebook
        run: |
          set -x
          conda run -n nlp-env jupyter nbconvert --to notebook --execute Scripts/web_scrapping.ipynb --output result.ipynb --debug 2>&1 | tee jupyter_output.log
        shell: bash
      
      - name: Display content of result.ipynb
        if: success()
        run: cat Scripts/result.ipynb
        shell: bash
      
      - name: Convert notebook to HTML
        if: success()
        run: |
          conda run -n nlp-env jupyter nbconvert --to html Scripts/result.ipynb
        shell: bash
      
      - name: Commit results
        if: success()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -f Scripts/result.ipynb Scripts/result.html Data/news.xlsx
          git commit -m "Daily NLP script run"
          git push https://$PAT@github.com/MMFreitas1/Analysis-of-Portuguese-news.git
        shell: bash
        env:
          PAT: ${{ secrets.PAT }}
      
      - name: Output Jupyter execution log
        if: failure()
        run: cat jupyter_output.log
